### ISSUE TITLE
🐞 : `Error: Expected a value of type 'Map<String, dynamic>', but got one of type 'String'` Error 

### ISSUE THREAD

**Issue by hemangjoshi37a** [lohanidamodar/flappwrite_account_kit#17]
Full error while runnig my flutter authkit app

```
Launching lib/main.dart on Chrome in debug mode...
package:teletest/main.dart:1
This app is linked to the debug service: ws://127.0.0.1:41535/g1YH8UNqwtA=/ws
Debug service listening on ws://127.0.0.1:41535/g1YH8UNqwtA=/ws
💪 Running with sound null safety 💪
Connecting to VM Service at ws://127.0.0.1:41535/g1YH8UNqwtA=/ws
Flutter Web Bootstrap: Programmatic
Failed to load font Roboto at https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf
TypeError: Failed to fetch
Error: Expected a value of type 'Map<String, dynamic>', but got one of type 'String'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 99:3        castError
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 452:10  cast
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/classes.dart 635:14     as_C
packages/appwrite/services/account.dart 23:27                                     get
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                <fn>
dart-sdk/lib/async/zone.dart 1653:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 766:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 795:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 566:5                                         [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 639:7                                         callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                                  _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                                   _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15               <fn>
```

my `pubspec.yaml` : 
```
name: teletest
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter 
  appwrite_auth_kit: 0.7.0
  random_string: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```
